font_size 15
cursor_blink_interval 0
cursor_trail 0
cursor_trail_start_threshold 4
copy_on_select yes
cursor_shape block
shell_integration no-cursor

background_opacity 0.7

# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="Iosevka Term"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
