font_size 16
cursor_blink_interval 0
cursor_trail 1
cursor_trail_start_decay 0.1 0.15
cursor_shape block
shell_integration no-cursor
scrollback_lines 100

mouse_hide_wait -1


foreground              #ffffff
background              #000000
selection_foreground    #ffffff
selection_background    #5a5a5a


url_color                #c4a7e7

active_tab_foreground    #e0def4
active_tab_background    #26233a
inactive_tab_foreground  #6e6a86
inactive_tab_background  #191724

# black
color0   #26233a
color8   #6e6a86

# red
color1   #eb6f92
color9   #eb6f92

# green
color2   #31748f
color10  #31748f

# yellow
color3   #f6c177
color11  #f6c177

# blue
color4   #9ccfd8
color12  #9ccfd8

# magenta
color5   #c4a7e7
color13  #c4a7e7

# cyan
color6   #ebbcba
color14  #ebbcba

# white
color7   #e0def4
color15  #e0def4
